"""empty message

Revision ID: 57095a97a6de
Revises: 8b3a2de2f167
Create Date: 2023-08-15 00:13:10.903419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57095a97a6de'
down_revision = '8b3a2de2f167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NEWS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.drop_column('conent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NEWS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conent', sa.TEXT(), nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
