"""empty message

Revision ID: 65e7a6ce4807
Revises: 7d30f461e0d9
Create Date: 2023-08-17 22:31:15.967389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e7a6ce4807'
down_revision = '7d30f461e0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CATEGORY', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_CATEGORY_id'), ['id'])

    with op.batch_alter_table('NEWS', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_NEWS_id'), ['id'])
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_USERS_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_USERS_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_USERS_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_USERS_id'), type_='unique')

    with op.batch_alter_table('NEWS', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'CATEGORY', ['type'], ['type'])
        batch_op.drop_constraint(batch_op.f('uq_NEWS_id'), type_='unique')
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('CATEGORY', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_CATEGORY_id'), type_='unique')

    # ### end Alembic commands ###
