"""empty message

Revision ID: 8b3a2de2f167
Revises: 
Create Date: 2023-08-04 02:18:16.388410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3a2de2f167'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NEWS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=345), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NEWS', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
